using Microsoft.EntityFrameworkCore;
using VehicleParts.Infrastructure;
using VehicleParts.Infrastructure.Data;
using VehicleParts.Application.Interfaces;
using VehicleParts.Application.Services.Customer;
using VehicleParts.Application.Services.Sales;

var builder = WebApplication.CreateBuilder(args);

// Add services
builder.Services.AddControllers();
builder.Services.AddOpenApi();

// Register Infrastructure Layer
builder.Services.AddInfrastructure(builder.Configuration);

// Register Application Services (AFTER Infrastructure)
builder.Services.AddScoped<ICustomerService, CustomerService>();
builder.Services.AddScoped<ISalesService, SalesService>();

// CORS for frontend
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var logger = scope.ServiceProvider
        .GetRequiredService<ILoggerFactory>()
        .CreateLogger("DatabaseStartup");

    try
    {
        await db.Database.MigrateAsync();
    }
    catch (Exception ex) when (app.Environment.IsDevelopment())
    {
        logger.LogWarning(
            ex,
            "Database migration skipped because the existing database schema does not match migration history.");
    }

    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "Notifications" (
            "NotificationId" integer GENERATED BY DEFAULT AS IDENTITY,
            "Message" character varying(500) NOT NULL,
            "Type" character varying(50) NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            "IsRead" boolean NOT NULL,
            "PartId" integer NULL,
            CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId"),
            CONSTRAINT "FK_Notifications_Parts_PartId" FOREIGN KEY ("PartId")
                REFERENCES "Parts" ("PartId") ON DELETE SET NULL
        );
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE INDEX IF NOT EXISTS "IX_Notifications_PartId"
            ON "Notifications" ("PartId");
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "PurchaseInvoices" (
            "PurchaseInvoiceId" integer GENERATED BY DEFAULT AS IDENTITY,
            "VendorId" integer NOT NULL,
            "PurchaseDate" timestamp with time zone NOT NULL,
            "TotalAmount" numeric NOT NULL,
            CONSTRAINT "PK_PurchaseInvoices" PRIMARY KEY ("PurchaseInvoiceId"),
            CONSTRAINT "FK_PurchaseInvoices_Vendors_VendorId" FOREIGN KEY ("VendorId")
                REFERENCES "Vendors" ("VendorId") ON DELETE RESTRICT
        );
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "PurchaseInvoiceItems" (
            "PurchaseInvoiceItemId" integer GENERATED BY DEFAULT AS IDENTITY,
            "PurchaseInvoiceId" integer NOT NULL,
            "PartId" integer NOT NULL,
            "Quantity" integer NOT NULL,
            "UnitPrice" numeric NOT NULL,
            "TotalPrice" numeric NOT NULL,
            CONSTRAINT "PK_PurchaseInvoiceItems" PRIMARY KEY ("PurchaseInvoiceItemId"),
            CONSTRAINT "FK_PurchaseInvoiceItems_PurchaseInvoices_PurchaseInvoiceId" FOREIGN KEY ("PurchaseInvoiceId")
                REFERENCES "PurchaseInvoices" ("PurchaseInvoiceId") ON DELETE CASCADE,
            CONSTRAINT "FK_PurchaseInvoiceItems_Parts_PartId" FOREIGN KEY ("PartId")
                REFERENCES "Parts" ("PartId") ON DELETE RESTRICT
        );
        """);

    await db.Database.ExecuteSqlRawAsync("""
        ALTER TABLE "PurchaseInvoiceItems"
            ADD COLUMN IF NOT EXISTS "TotalPrice" numeric NOT NULL DEFAULT 0;
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE INDEX IF NOT EXISTS "IX_PurchaseInvoices_VendorId"
            ON "PurchaseInvoices" ("VendorId");
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE INDEX IF NOT EXISTS "IX_PurchaseInvoiceItems_PurchaseInvoiceId"
            ON "PurchaseInvoiceItems" ("PurchaseInvoiceId");
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE INDEX IF NOT EXISTS "IX_PurchaseInvoiceItems_PartId"
            ON "PurchaseInvoiceItems" ("PartId");
        """);

    await DbSeeder.SeedAsync(scope.ServiceProvider);
}

// Configure pipeline
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseHttpsRedirection();

app.UseCors("AllowFrontend");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();
