using Microsoft.EntityFrameworkCore;
using VehicleParts.Application.Middlewares;
using VehicleParts.Infrastructure;
using VehicleParts.Infrastructure.Data;

var builder = WebApplication.CreateBuilder(args);

// Services
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddOpenApi();

builder.Services.AddInfrastructure(
    builder.Configuration
);

// CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});

var app = builder.Build();

// Database + Seeder
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var logger = scope.ServiceProvider
        .GetRequiredService<ILoggerFactory>()
        .CreateLogger("DatabaseStartup");

    try
    {
        await db.Database.MigrateAsync();
        await EnsureAdminTablesAsync(db);
        await DbSeeder.SeedAsync(scope.ServiceProvider);
    }
    catch (Exception ex) when (app.Environment.IsDevelopment())
    {
        logger.LogWarning(
            ex,
            "Database migration/seeding skipped because the database is not reachable or the schema is not ready.");
    }
}

async Task EnsureAdminTablesAsync(AppDbContext db)
{
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "Notifications" (
            "NotificationId" integer GENERATED BY DEFAULT AS IDENTITY,
            "Message" character varying(500) NOT NULL,
            "Type" character varying(50) NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            "IsRead" boolean NOT NULL,
            "PartId" integer NULL,
            CONSTRAINT "PK_Notifications" PRIMARY KEY ("NotificationId"),
            CONSTRAINT "FK_Notifications_Parts_PartId" FOREIGN KEY ("PartId")
                REFERENCES "Parts" ("PartId") ON DELETE SET NULL
        );
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE INDEX IF NOT EXISTS "IX_Notifications_PartId"
            ON "Notifications" ("PartId");
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "PurchaseInvoices" (
            "PurchaseInvoiceId" integer GENERATED BY DEFAULT AS IDENTITY,
            "VendorId" integer NOT NULL,
            "PurchaseDate" timestamp with time zone NOT NULL,
            "TotalAmount" numeric NOT NULL,
            CONSTRAINT "PK_PurchaseInvoices" PRIMARY KEY ("PurchaseInvoiceId"),
            CONSTRAINT "FK_PurchaseInvoices_Vendors_VendorId" FOREIGN KEY ("VendorId")
                REFERENCES "Vendors" ("VendorId") ON DELETE RESTRICT
        );
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "PurchaseInvoiceItems" (
            "PurchaseInvoiceItemId" integer GENERATED BY DEFAULT AS IDENTITY,
            "PurchaseInvoiceId" integer NOT NULL,
            "PartId" integer NOT NULL,
            "Quantity" integer NOT NULL,
            "UnitPrice" numeric NOT NULL,
            "TotalPrice" numeric NOT NULL,
            CONSTRAINT "PK_PurchaseInvoiceItems" PRIMARY KEY ("PurchaseInvoiceItemId"),
            CONSTRAINT "FK_PurchaseInvoiceItems_PurchaseInvoices_PurchaseInvoiceId" FOREIGN KEY ("PurchaseInvoiceId")
                REFERENCES "PurchaseInvoices" ("PurchaseInvoiceId") ON DELETE CASCADE,
            CONSTRAINT "FK_PurchaseInvoiceItems_Parts_PartId" FOREIGN KEY ("PartId")
                REFERENCES "Parts" ("PartId") ON DELETE RESTRICT
        );
        """);

    await db.Database.ExecuteSqlRawAsync("""
        ALTER TABLE "PurchaseInvoiceItems"
            ADD COLUMN IF NOT EXISTS "TotalPrice" numeric NOT NULL DEFAULT 0;
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE INDEX IF NOT EXISTS "IX_PurchaseInvoices_VendorId"
            ON "PurchaseInvoices" ("VendorId");
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE INDEX IF NOT EXISTS "IX_PurchaseInvoiceItems_PurchaseInvoiceId"
            ON "PurchaseInvoiceItems" ("PurchaseInvoiceId");
        """);

    await db.Database.ExecuteSqlRawAsync("""
        CREATE INDEX IF NOT EXISTS "IX_PurchaseInvoiceItems_PartId"
            ON "PurchaseInvoiceItems" ("PartId");
        """);
}

// OpenAPI
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

// Middleware
app.UseMiddleware<ExceptionHandlingMiddleware>();

app.UseHttpsRedirection();
app.UseCors("AllowFrontend");

app.UseAuthentication();
app.UseAuthorization();

app.UseStaticFiles();

app.MapControllers();

app.Run();
